[app]
# app settings are global available like `r2r_config.agent.app`
# project_name = "r2r_default" # optional, can also set with `R2R_PROJECT_NAME` env var
default_max_documents_per_user = 10_000
default_max_chunks_per_user = 10_000_000
default_max_collections_per_user = 5_000

# Set the default max upload size to 20 GB for local testing
default_max_upload_size = 21474836480

# LLM used for internal operations, like deriving conversation names
fast_llm = "ollama/llama3.1"

# LLM used for user-facing output, like RAG replies
quality_llm = "ollama/deepseek-r1"

# LLM used for ingesting visual inputs
vlm = "ollama/deepseek-r1"

# LLM used for transcription
audio_lm = "ollama/whisper-1"

[agent]
agent_static_prompt = "rag_agent"
# tools = ["local_search", "content", "web_search"]
tools = ["local_search"]

[auth]
provider = "r2r"
access_token_lifetime_in_minutes = 60000
refresh_token_lifetime_in_days = 7
require_authentication = false
require_email_verification = false
default_admin_email = "admin@example.com"
default_admin_password = "change_me_immediately"

[completion]
provider = "r2r"
concurrent_request_limit = 4

  [completion.generation_config]
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 4_096
  stream = false
  add_generation_kwargs = { }

[crypto]
provider = "bcrypt"

[database]
default_collection_name = "Default"
default_collection_description = "Your default collection."

  [database.graph_creation_settings]
    clustering_mode = "local"
    graph_entity_description_prompt = "graphrag_entity_description"
    entity_types = [] # if empty, all entities are extracted
    relation_types = [] # if empty, all relations are extracted
    max_description_input_length = 65536
    automatic_deduplication = true # enable automatic deduplication of entities

  [database.graph_enrichment_settings]
    max_summary_input_length = 65536
    leiden_params = {}

  [database.limits]
    # Default fallback limits if no route or user-level overrides are found
    global_per_min = 300
    monthly_limit = 10000

  [database.route_limits]
    # Set the `v3/retrieval/search` route to have a maximum of 5 requests per minute
    "/v3/retrieval/search" = { route_per_min = 120 }
    "/v3/retrieval/rag" = { route_per_min = 30 }

[embedding]
provider = "ollama"
base_model = "mxbai-embed-large"
base_dimension = 1_024
batch_size = 128
add_title_as_prefix = true
concurrent_request_limit = 2

[completion_embedding]
# Generally this should be the same as the embedding config, but advanced users may want to run with a different provider to reduce latency
provider = "ollama"
base_model = "mxbai-embed-large"
base_dimension = 1_024
batch_size = 128
add_title_as_prefix = true
concurrent_request_limit = 2

[file]
provider = "postgres"

[ingestion]
provider = "r2r"
chunking_strategy = "recursive"
chunk_size = 1_024
chunk_overlap = 512
excluded_parsers = ["mp4"]
automatic_extraction = true # enable automatic extraction of entities and relations

  [ingestion.chunk_enrichment_settings]
    enable_chunk_enrichment = false # disabled by default
    n_chunks = 2 # the number of chunks (both preceeding and succeeding) to use in enrichment

  [ingestion.extra_parsers]
    pdf = "zerox"

[logging]
provider = "r2r"
log_table = "logs"
log_info_table = "log_info"

[orchestration]
provider = "simple"

[prompt]
provider = "r2r"

[email]
provider = "console_mock"
