name: 'Setup Python for R2R Light'
description: 'Sets up Python environment and installs dependencies using Poetry'
inputs:
  os:
    description: 'Operating system'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry and dependencies on Ubuntu and macOS
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        cd py && poetry install -E core -E ingestion-bundle
