name: Build and Publish Development Docker Image

on:
  push:
    branches:
        - '**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [ self-hosted, Linux ]
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Docker Auth
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.RAGTORICHES_DOCKER_UNAME }}
        password: ${{ secrets.RAGTORICHES_DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set image name
      id: image
      run: |
        echo "IMAGE_NAME=ragtoriches/dev" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ragtoriches/dev:latest
        platforms: linux/amd64
        no-cache: true
        pull: true
