name: CI

on:
  push:
    branches:
      - main
      - '**/feature/*'
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: [ self-hosted, Linux ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          poetry install

      - name: Install pre-commit
        run: poetry run pre-commit install

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Cleanup
        if: always()
        run: |
          deactivate
          rm -rf venv

  pytest:
    runs-on: [ self-hosted, Linux ]
    timeout-minutes: 15

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_VECS_COLLECTION: ${{ secrets.POSTGRES_VECS_COLLECTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          poetry install

      - name: Start Ollama server
        run: |
          ollama serve &
          sleep 5
          curl -i http://localhost:11434

      - name: Run tests
        run: poetry run pytest tests/ -k "not redis and not sentence_transformer"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          deactivate
          rm -rf venv
          pkill -f ollama || true
          echo "Cleaned up Ollama server"
