name: R2R Light Python Integration Test (ubuntu)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - dev-minor
      - main
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
      AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
      AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
      TELEMETRY_ENABLED: 'false'
      R2R_POSTGRES_HOST: localhost
      R2R_POSTGRES_DBNAME: postgres
      R2R_POSTGRES_PORT: '5432'
      R2R_POSTGRES_PASSWORD: postgres
      R2R_POSTGRES_USER: postgres
      R2R_PROJECT_NAME: r2r_default

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        uses: ./.github/actions/setup-python-light

      - name: Setup and start PostgreSQL
        uses: ./.github/actions/setup-postgres-ext

      - name: Start R2R Light server
        uses: ./.github/actions/start-r2r-light

      - name: Run R2R Full Python Integration Test
        run: |
          poetry run pytest
