name: R2R Full Python Integration Test (ubuntu)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - dev-minor
      - main
  workflow_dispatch:

jobs:
  integration-test:    # or whatever name you want to give this job
    runs-on: ubuntu-latest
    env:
      TELEMETRY_ENABLED: 'false'
      R2R_PROJECT_NAME: r2r_default
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
      AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
      AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        uses: ./.github/actions/setup-python-full

      - name: Setup and start Docker
        uses: ./.github/actions/setup-docker

      - name: Login Docker
        uses: ./.github/actions/login-docker
        with:
          docker_username: ${{ secrets.RAGTORICHES_DOCKER_UNAME }}
          docker_password: ${{ secrets.RAGTORICHES_DOCKER_TOKEN }}

      - name: Start R2R Full server
        uses: ./.github/actions/start-r2r-full

      - name: Run R2R Full Python Integration Test
        run: |
          poetry run pytest
